### ISSUE TITLE
README file points to screenshot URLs returning 404

### ISSUE THREAD

**Issue by kucharskim** [jorisvink/coma#1]
Could you commit screenshot files locally to the repo?

**Comment by jorisvink** [comment]
fixed in latest master.

**Comment by kiwec** [comment]
The links still work, however GitHub's image proxy now fails to load the images.

https://help.github.com/en/articles/about-anonymized-image-urls#troubleshooting-issues-with-camo

**Comment by jorisvink** [comment]
This was probably related to an outgoing cert on the coma.one domain. That’s resolved.

.joris
